# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\abi\tools\ui\uifileconverter.ui'
#
# Created: Tue Aug  7 14:54:08 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_UiFileConverter(object):
    def setupUi(self, UiFileConverter):
        UiFileConverter.setObjectName("UiFileConverter")
        UiFileConverter.resize(816, 579)
        self.centralwidget = QtGui.QWidget(UiFileConverter)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ui_frame = QtGui.QFrame(self.centralwidget)
        self.ui_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ui_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.ui_frame.setObjectName("ui_frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.ui_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiFile_label = QtGui.QLabel(self.ui_frame)
        self.uiFile_label.setObjectName("uiFile_label")
        self.horizontalLayout.addWidget(self.uiFile_label)
        self.uiFile_comboBox = QtGui.QComboBox(self.ui_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiFile_comboBox.sizePolicy().hasHeightForWidth())
        self.uiFile_comboBox.setSizePolicy(sizePolicy)
        self.uiFile_comboBox.setObjectName("uiFile_comboBox")
        self.horizontalLayout.addWidget(self.uiFile_comboBox)
        self.verticalLayout.addWidget(self.ui_frame)
        self.sideBySide_groupBox = QtGui.QGroupBox(self.centralwidget)
        self.sideBySide_groupBox.setCheckable(True)
        self.sideBySide_groupBox.setObjectName("sideBySide_groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.sideBySide_groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.outDir_label = QtGui.QLabel(self.sideBySide_groupBox)
        self.outDir_label.setObjectName("outDir_label")
        self.horizontalLayout_3.addWidget(self.outDir_label)
        self.outDir_lineEdit = QtGui.QLineEdit(self.sideBySide_groupBox)
        self.outDir_lineEdit.setObjectName("outDir_lineEdit")
        self.horizontalLayout_3.addWidget(self.outDir_lineEdit)
        self.outDir_pushButton = QtGui.QPushButton(self.sideBySide_groupBox)
        self.outDir_pushButton.setObjectName("outDir_pushButton")
        self.horizontalLayout_3.addWidget(self.outDir_pushButton)
        self.verticalLayout.addWidget(self.sideBySide_groupBox)
        self.patchResourcesImport_groupBox = QtGui.QGroupBox(self.centralwidget)
        self.patchResourcesImport_groupBox.setObjectName("patchResourcesImport_groupBox")
        self.formLayout = QtGui.QFormLayout(self.patchResourcesImport_groupBox)
        self.formLayout.setObjectName("formLayout")
        self.repairString_label = QtGui.QLabel(self.patchResourcesImport_groupBox)
        self.repairString_label.setObjectName("repairString_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.repairString_label)
        self.repairString_lineEdit = QtGui.QLineEdit(self.patchResourcesImport_groupBox)
        self.repairString_lineEdit.setObjectName("repairString_lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.repairString_lineEdit)
        self.verticalLayout.addWidget(self.patchResourcesImport_groupBox)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uiFile_pushButton = QtGui.QPushButton(self.groupBox)
        self.uiFile_pushButton.setObjectName("uiFile_pushButton")
        self.horizontalLayout_4.addWidget(self.uiFile_pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 130, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.screen_label = QtGui.QLabel(self.centralwidget)
        self.screen_label.setText("")
        self.screen_label.setObjectName("screen_label")
        self.verticalLayout.addWidget(self.screen_label)
        spacerItem2 = QtGui.QSpacerItem(20, 129, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.quit_frame = QtGui.QFrame(self.centralwidget)
        self.quit_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.quit_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.quit_frame.setObjectName("quit_frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.quit_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settings_pushButton = QtGui.QPushButton(self.quit_frame)
        self.settings_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/settings_grey_48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_pushButton.setIcon(icon)
        self.settings_pushButton.setObjectName("settings_pushButton")
        self.horizontalLayout_2.addWidget(self.settings_pushButton)
        spacerItem3 = QtGui.QSpacerItem(457, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.quit_frame)
        UiFileConverter.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(UiFileConverter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        UiFileConverter.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(UiFileConverter)
        self.statusbar.setObjectName("statusbar")
        UiFileConverter.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(UiFileConverter)
        self.action_Open.setObjectName("action_Open")
        self.actionOpen_recent = QtGui.QAction(UiFileConverter)
        self.actionOpen_recent.setObjectName("actionOpen_recent")
        self.action_Quit = QtGui.QAction(UiFileConverter)
        self.action_Quit.setObjectName("action_Quit")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.actionOpen_recent)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(UiFileConverter)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("activated()"), UiFileConverter.close)
        QtCore.QMetaObject.connectSlotsByName(UiFileConverter)

    def retranslateUi(self, UiFileConverter):
        UiFileConverter.setWindowTitle(QtGui.QApplication.translate("UiFileConverter", "UI File Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFile_label.setText(QtGui.QApplication.translate("UiFileConverter", "UI File:", None, QtGui.QApplication.UnicodeUTF8))
        self.sideBySide_groupBox.setTitle(QtGui.QApplication.translate("UiFileConverter", "side-by-side output", None, QtGui.QApplication.UnicodeUTF8))
        self.outDir_label.setText(QtGui.QApplication.translate("UiFileConverter", "Output directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.outDir_pushButton.setText(QtGui.QApplication.translate("UiFileConverter", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.patchResourcesImport_groupBox.setTitle(QtGui.QApplication.translate("UiFileConverter", "Patch resources import", None, QtGui.QApplication.UnicodeUTF8))
        self.repairString_label.setText(QtGui.QApplication.translate("UiFileConverter", "Repair string:", None, QtGui.QApplication.UnicodeUTF8))
        self.repairString_lineEdit.setPlaceholderText(QtGui.QApplication.translate("UiFileConverter", "Leave empty if the resource import does not need patching", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFile_pushButton.setText(QtGui.QApplication.translate("UiFileConverter", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("UiFileConverter", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("UiFileConverter", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_recent.setText(QtGui.QApplication.translate("UiFileConverter", "Open recent", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("UiFileConverter", "&Quit", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
